name: AronsBlog
description: Arons occasionally writes.

markdown: redcarpet
pygments: true

url: http://arons.github.io

paginate: 10

layout: default

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#        
analytics :
  provider : google
  google : 
      tracking_id : 'UA-24741902-1'
  getclicky :
    site_id :