#!/bin/bash

jekyll build

echo "checkout master"
git checkout master

echo "update site content"
cp -r _site/* ./

echo "add missing files"
git add -A



STATUS=$(git status)
echo "status:"
echo "${STATUS}"
echo "commit!"
git commit -a -m "sync master, status: 
${STATUS}"

echo "checkout source branch"
git checkout source